apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
        - name: namenode
          image: hadoop-cluster
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - |
              hdfs namenode -format -force
              start-dfs.sh
              tail -f /dev/null
          ports:
            - containerPort: 9870
          volumeMounts:
            - name: namenode-storage
              mountPath: /hadoop/dfs/name
      volumes:
        - name: namenode-storage
          persistentVolumeClaim:
            claimName: namenode-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  type: NodePort
  ports:
    - port: 9870
      targetPort: 9870
      nodePort: 30007
  selector:
    app: hadoop-namenode
